use std::fs;

use assert_cmd::Command;
use predicates::prelude::*;

fn btpc() -> Command {
    Command::cargo_bin("btpc").unwrap()
}

fn isolated() -> (tempfile::TempDir, Command) {
    let home = tempfile::tempdir().unwrap();
    let mut command = btpc();
    command
        .env("HOME", home.path())
        .env("XDG_CONFIG_HOME", home.path().join("config"))
        .env("XDG_DATA_HOME", home.path().join("data"))
        .env_remove("SHELL")
        .env_remove("PSModulePath")
        .arg("--no-config");
    (home, command)
}

#[test]
fn generate_matches_hidden_compatibility_alias_for_every_shell() {
    for shell in ["bash", "zsh", "fish", "powershell", "elvish"] {
        let generated = btpc()
            .args(["--no-config", "completion", "generate", shell])
            .output()
            .unwrap();
        let alias = btpc()
            .args(["--no-config", "completions", shell])
            .output()
            .unwrap();
        assert!(generated.status.success(), "{shell}");
        assert_eq!(generated.stdout, alias.stdout, "{shell}");
        assert!(String::from_utf8_lossy(&alias.stderr).contains("deprecated"));
    }
}

#[test]
fn install_dry_run_detects_shell_without_writing() {
    let (home, mut command) = isolated();
    command
        .env("SHELL", "/bin/fish")
        .args(["completion", "install", "--dry-run"])
        .assert()
        .success()
        .stdout(predicate::str::contains("btpc.fish"))
        .stdout(predicate::str::contains("generated by btpc"));
    assert!(
        !home
            .path()
            .join("config/fish/completions/btpc.fish")
            .exists()
    );
}

#[test]
fn install_is_atomic_and_refuses_unrelated_content_without_force() {
    let (home, mut command) = isolated();
    command
        .args(["completion", "install", "fish"])
        .assert()
        .success();
    let target = home.path().join("config/fish/completions/btpc.fish");
    let generated = fs::read_to_string(&target).unwrap();
    assert!(generated.starts_with("# generated by btpc\n"));

    fs::write(&target, "user content\n").unwrap();
    let (_, mut refusal) = isolated();
    refusal
        .env("HOME", home.path())
        .env("XDG_CONFIG_HOME", home.path().join("config"));
    refusal
        .args(["completion", "install", "fish"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("not BTPC-generated"));
    assert_eq!(fs::read_to_string(&target).unwrap(), "user content\n");

    let (_, mut forced) = isolated();
    forced
        .env("HOME", home.path())
        .env("XDG_CONFIG_HOME", home.path().join("config"));
    forced
        .args(["completion", "install", "fish", "--force"])
        .assert()
        .success();
    assert!(
        fs::read_to_string(target)
            .unwrap()
            .starts_with("# generated by btpc\n")
    );
}

#[test]
fn uninstall_only_removes_btpc_generated_files() {
    let (home, mut install) = isolated();
    install
        .args(["completion", "install", "zsh"])
        .assert()
        .success();
    let target = home.path().join("data/zsh/site-functions/_btpc");
    assert!(target.exists());

    let (_, mut dry_run) = isolated();
    dry_run
        .env("HOME", home.path())
        .env("XDG_DATA_HOME", home.path().join("data"));
    dry_run
        .args(["completion", "uninstall", "zsh", "--dry-run"])
        .assert()
        .success()
        .stdout(predicate::str::contains("_btpc"));
    assert!(target.exists());

    let (_, mut uninstall) = isolated();
    uninstall
        .env("HOME", home.path())
        .env("XDG_DATA_HOME", home.path().join("data"));
    uninstall
        .args(["completion", "uninstall", "zsh"])
        .assert()
        .success();
    assert!(!target.exists());

    fs::create_dir_all(target.parent().unwrap()).unwrap();
    fs::write(&target, "user content\n").unwrap();
    let (_, mut unsafe_remove) = isolated();
    unsafe_remove
        .env("HOME", home.path())
        .env("XDG_DATA_HOME", home.path().join("data"));
    unsafe_remove
        .args(["completion", "uninstall", "zsh"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("not BTPC-generated"));
    assert!(target.exists());
}

#[test]
fn ambiguous_shell_detection_requests_an_explicit_shell() {
    let (_home, mut command) = isolated();
    command
        .args(["completion", "install"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("specify a shell"));
}
