use std::env;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use btpc_core::Error;
use btpc_core::create::{DurabilityPolicy, OverwritePolicy, write_atomic};
use clap::CommandFactory as _;
use clap_complete::Shell;

use crate::command::{Cli, CompletionMutationArgs};

const MARKER: &str = "# generated by btpc\n";

pub(crate) fn completion_bytes(shell: Shell) -> Vec<u8> {
    let mut output = Vec::new();
    clap_complete::generate(shell, &mut Cli::command(), "btpc", &mut output);
    output
}

pub(crate) fn generate(shell: Shell) -> Result<(), Error> {
    std::io::stdout()
        .write_all(&completion_bytes(shell))
        .map_err(|source| Error::io("<stdout>", source))
}

// Spec: CLI-COMPLETE-001
pub(crate) fn install(arguments: &CompletionMutationArgs) -> Result<(), Error> {
    let shell = resolve_shell(arguments.shell)?;
    let destination = completion_path(shell)?;
    let mut content = MARKER.as_bytes().to_vec();
    content.extend(completion_bytes(shell));
    if arguments.dry_run {
        println!("Target: {}", destination.display());
        std::io::stdout()
            .write_all(&content)
            .map_err(|source| Error::io("<stdout>", source))?;
        println!("Install this file without modifying shell startup files.");
        return Ok(());
    }
    if destination.exists() && !arguments.force {
        let existing = fs::read(&destination).map_err(|source| Error::io(&destination, source))?;
        if !existing.starts_with(MARKER.as_bytes()) {
            return Err(Error::metainfo_field(
                "completion",
                format!(
                    "{} is not BTPC-generated; pass --force to replace it",
                    destination.display()
                ),
            ));
        }
    }
    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent).map_err(|source| Error::io(parent, source))?;
    }
    write_atomic(
        &destination,
        &content,
        if destination.exists() {
            OverwritePolicy::Replace
        } else {
            OverwritePolicy::Deny
        },
        DurabilityPolicy::FileAndDirectory,
    )?;
    println!(
        "Installed {} completions at {}",
        shell_name(shell),
        destination.display()
    );
    Ok(())
}

pub(crate) fn uninstall(arguments: &CompletionMutationArgs) -> Result<(), Error> {
    let shell = resolve_shell(arguments.shell)?;
    let destination = completion_path(shell)?;
    if !destination.exists() {
        println!("No BTPC completion file at {}", destination.display());
        return Ok(());
    }
    let existing = fs::read(&destination).map_err(|source| Error::io(&destination, source))?;
    if !existing.starts_with(MARKER.as_bytes()) {
        return Err(Error::metainfo_field(
            "completion",
            format!(
                "{} is not BTPC-generated; refusing to remove it",
                destination.display()
            ),
        ));
    }
    if arguments.dry_run {
        println!("Would remove {}", destination.display());
        return Ok(());
    }
    fs::remove_file(&destination).map_err(|source| Error::io(&destination, source))?;
    println!("Removed {}", destination.display());
    Ok(())
}

fn resolve_shell(explicit: Option<Shell>) -> Result<Shell, Error> {
    if let Some(shell) = explicit {
        return Ok(shell);
    }
    let mut detected = Vec::new();
    if let Some(value) = env::var_os("SHELL") {
        if let Some(shell) =
            shell_from_hint(Path::new(&value).file_name().and_then(|name| name.to_str()))
        {
            detected.push(shell);
        }
    }
    if env::var_os("PSModulePath").is_some() {
        detected.push(Shell::PowerShell);
    }
    detected.dedup_by_key(|shell| shell_name(*shell));
    match detected.as_slice() {
        [shell] => Ok(*shell),
        _ => Err(Error::metainfo_field(
            "completion.shell",
            "cannot determine shell unambiguously; specify a shell explicitly",
        )),
    }
}

fn shell_from_hint(hint: Option<&str>) -> Option<Shell> {
    match hint?.to_ascii_lowercase().as_str() {
        "bash" => Some(Shell::Bash),
        "zsh" => Some(Shell::Zsh),
        "fish" => Some(Shell::Fish),
        "pwsh" | "powershell" | "powershell.exe" | "pwsh.exe" => Some(Shell::PowerShell),
        "elvish" => Some(Shell::Elvish),
        _ => None,
    }
}

fn completion_path(shell: Shell) -> Result<PathBuf, Error> {
    let home = env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .ok_or_else(|| {
            Error::metainfo_field("completion", "cannot determine user home directory")
        })?;
    let config = env::var_os("XDG_CONFIG_HOME").map_or_else(|| home.join(".config"), PathBuf::from);
    let data =
        env::var_os("XDG_DATA_HOME").map_or_else(|| home.join(".local/share"), PathBuf::from);
    Ok(match shell {
        Shell::Bash => data.join("bash-completion/completions/btpc"),
        Shell::Zsh => data.join("zsh/site-functions/_btpc"),
        Shell::Fish => config.join("fish/completions/btpc.fish"),
        Shell::PowerShell => home.join("Documents/PowerShell/Completions/btpc.ps1"),
        Shell::Elvish => config.join("elvish/lib/btpc.elv"),
        _ => return Err(Error::unsupported("unsupported completion shell")),
    })
}

const fn shell_name(shell: Shell) -> &'static str {
    match shell {
        Shell::Bash => "bash",
        Shell::Zsh => "zsh",
        Shell::Fish => "fish",
        Shell::PowerShell => "powershell",
        Shell::Elvish => "elvish",
        _ => "unknown",
    }
}

pub(crate) fn manpage() -> Result<(), Error> {
    clap_mangen::Man::new(Cli::command())
        .render(&mut std::io::stdout())
        .map_err(|source| Error::io("<stdout>", source))
}
