use std::env;
use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use btpc_core::Error;
use btpc_core::create::{DurabilityPolicy, OverwritePolicy, write_atomic};
use clap::{Arg, Command, CommandFactory as _};
use clap_complete::Shell;

use crate::command::{Cli, CompletionMutationArgs};
use crate::output::safe_path_display;

const MARKER: &str = "# generated by btpc\n";

pub(crate) fn completion_bytes(shell: Shell) -> Vec<u8> {
    let mut output = Vec::new();
    clap_complete::generate(shell, &mut Cli::command(), "btpc", &mut output);
    output
}

pub(crate) fn generate(shell: Shell) -> Result<(), Error> {
    std::io::stdout()
        .write_all(&completion_bytes(shell))
        .map_err(|source| Error::io("<stdout>", source))
}

// Spec: CLI-COMPLETE-001
pub(crate) fn install(arguments: &CompletionMutationArgs) -> Result<(), Error> {
    let shell = resolve_shell(arguments.shell)?;
    let destination = completion_path(shell)?;
    let mut content = MARKER.as_bytes().to_vec();
    content.extend(completion_bytes(shell));
    if arguments.dry_run {
        println!("Target: {}", safe_path_display(&destination));
        std::io::stdout()
            .write_all(&content)
            .map_err(|source| Error::io("<stdout>", source))?;
        println!("Install this file without modifying shell startup files.");
        return Ok(());
    }
    if destination.exists() && !arguments.force {
        let existing = fs::read(&destination).map_err(|source| Error::io(&destination, source))?;
        if !existing.starts_with(MARKER.as_bytes()) {
            return Err(Error::metainfo_field(
                "completion",
                format!(
                    "{} is not BTPC-generated; pass --force to replace it",
                    safe_path_display(&destination)
                ),
            ));
        }
    }
    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent).map_err(|source| Error::io(parent, source))?;
    }
    write_atomic(
        &destination,
        &content,
        if destination.exists() {
            OverwritePolicy::Replace
        } else {
            OverwritePolicy::Deny
        },
        DurabilityPolicy::FileAndDirectory,
    )?;
    println!(
        "Installed {} completions at {}",
        shell_name(shell),
        safe_path_display(&destination)
    );
    Ok(())
}

pub(crate) fn uninstall(arguments: &CompletionMutationArgs) -> Result<(), Error> {
    let shell = resolve_shell(arguments.shell)?;
    let destination = completion_path(shell)?;
    if !destination.exists() {
        println!(
            "No BTPC completion file at {}",
            safe_path_display(&destination)
        );
        return Ok(());
    }
    let existing = fs::read(&destination).map_err(|source| Error::io(&destination, source))?;
    if !existing.starts_with(MARKER.as_bytes()) {
        return Err(Error::metainfo_field(
            "completion",
            format!(
                "{} is not BTPC-generated; refusing to remove it",
                safe_path_display(&destination)
            ),
        ));
    }
    if arguments.dry_run {
        println!("Would remove {}", safe_path_display(&destination));
        return Ok(());
    }
    fs::remove_file(&destination).map_err(|source| Error::io(&destination, source))?;
    println!("Removed {}", safe_path_display(&destination));
    Ok(())
}

fn resolve_shell(explicit: Option<Shell>) -> Result<Shell, Error> {
    if let Some(shell) = explicit {
        return Ok(shell);
    }
    let mut detected = Vec::new();
    if let Some(value) = env::var_os("SHELL") {
        if let Some(shell) =
            shell_from_hint(Path::new(&value).file_name().and_then(|name| name.to_str()))
        {
            detected.push(shell);
        }
    }
    if env::var_os("PSModulePath").is_some() {
        detected.push(Shell::PowerShell);
    }
    detected.dedup_by_key(|shell| shell_name(*shell));
    match detected.as_slice() {
        [shell] => Ok(*shell),
        _ => Err(Error::metainfo_field(
            "completion.shell",
            "cannot determine shell unambiguously; specify a shell explicitly",
        )),
    }
}

fn shell_from_hint(hint: Option<&str>) -> Option<Shell> {
    match hint?.to_ascii_lowercase().as_str() {
        "bash" => Some(Shell::Bash),
        "zsh" => Some(Shell::Zsh),
        "fish" => Some(Shell::Fish),
        "pwsh" | "powershell" | "powershell.exe" | "pwsh.exe" => Some(Shell::PowerShell),
        "elvish" => Some(Shell::Elvish),
        _ => None,
    }
}

fn completion_path(shell: Shell) -> Result<PathBuf, Error> {
    let home = env::var_os("HOME")
        .or_else(|| env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .ok_or_else(|| {
            Error::metainfo_field("completion", "cannot determine user home directory")
        })?;
    let config = env::var_os("XDG_CONFIG_HOME").map_or_else(|| home.join(".config"), PathBuf::from);
    let data =
        env::var_os("XDG_DATA_HOME").map_or_else(|| home.join(".local/share"), PathBuf::from);
    Ok(match shell {
        Shell::Bash => data.join("bash-completion/completions/btpc"),
        Shell::Zsh => data.join("zsh/site-functions/_btpc"),
        Shell::Fish => config.join("fish/completions/btpc.fish"),
        Shell::PowerShell => home.join("Documents/PowerShell/Completions/btpc.ps1"),
        Shell::Elvish => config.join("elvish/lib/btpc.elv"),
        _ => return Err(Error::unsupported("unsupported completion shell")),
    })
}

const fn shell_name(shell: Shell) -> &'static str {
    match shell {
        Shell::Bash => "bash",
        Shell::Zsh => "zsh",
        Shell::Fish => "fish",
        Shell::PowerShell => "powershell",
        Shell::Elvish => "elvish",
        _ => "unknown",
    }
}

pub(crate) fn manpage() -> Result<(), Error> {
    clap_mangen::Man::new(Cli::command())
        .render(&mut std::io::stdout())
        .map_err(|source| Error::io("<stdout>", source))
}

pub(crate) fn markdown(destination: &Path) -> Result<(), Error> {
    if destination.exists() {
        fs::remove_dir_all(destination).map_err(|source| Error::io(destination, source))?;
    }
    fs::create_dir_all(destination).map_err(|source| Error::io(destination, source))?;

    let mut root = Cli::command().term_width(100);
    root.build();
    write_markdown_tree(&root, &[], destination)
}

fn write_markdown_tree(
    command: &Command,
    path: &[String],
    destination: &Path,
) -> Result<(), Error> {
    let file = destination.join(markdown_filename(path));
    fs::write(&file, render_markdown(command, path)).map_err(|source| Error::io(&file, source))?;
    for child in visible_subcommands(command) {
        let mut child_path = path.to_vec();
        child_path.push(child.get_name().to_owned());
        write_markdown_tree(child, &child_path, destination)?;
    }
    Ok(())
}

fn render_markdown(command: &Command, path: &[String]) -> String {
    let command_invocation = invocation(path);
    let mut output = format!(
        "---\ntitle: {command_invocation} command reference\n---\n\n# `{command_invocation}`\n\n<!-- Generated by `scripts/generate-cli-reference.sh`; do not edit. -->\n\n"
    );
    if let Some(about) = command.get_long_about().or_else(|| command.get_about()) {
        writeln!(output, "{}\n", about.to_string().trim())
            .expect("writing to a String cannot fail");
    }
    if !path.is_empty() {
        let parent = &path[..path.len() - 1];
        write!(
            output,
            "**Parent:** [`{}`]({})\n\n",
            invocation(parent),
            markdown_filename(parent)
        )
        .expect("writing to a String cannot fail");
    }
    output.push_str(
        "See [Configuration and global flags](../configuration.md) and \
[Exit codes and streams](../index.md#exit-codes-and-streams).\n\n",
    );

    let mut usage = command.clone();
    let synopsis = usage.render_usage().to_string();
    output.push_str("## Synopsis\n\n```text\n");
    output.push_str(synopsis.trim());
    output.push_str("\n```\n\n");

    let subcommands = visible_subcommands(command).collect::<Vec<_>>();
    if !subcommands.is_empty() {
        output.push_str("## Subcommands\n\n| Command | Description |\n| --- | --- |\n");
        for child in subcommands {
            let mut child_path = path.to_vec();
            child_path.push(child.get_name().to_owned());
            writeln!(
                output,
                "| [`{}`]({}) | {} |\n",
                invocation(&child_path),
                markdown_filename(&child_path),
                command_about(child)
            )
            .expect("writing to a String cannot fail");
        }
        output.push('\n');
    }

    let aliases = command
        .get_subcommands()
        .filter(|child| child.is_hide_set() && !child.get_name().starts_with("__"))
        .collect::<Vec<_>>();
    if !aliases.is_empty() {
        output.push_str("## Deprecated aliases\n\n");
        for alias in aliases {
            let mut alias_path = path.to_vec();
            alias_path.push(alias.get_name().to_owned());
            writeln!(
                output,
                "- `{}` — {}\n",
                invocation(&alias_path),
                command_about(alias)
            )
            .expect("writing to a String cannot fail");
        }
        output.push('\n');
    }

    render_arguments(&mut output, command, false);
    render_arguments(&mut output, command, true);
    writeln!(
        output,
        "## Example\n\n```console\n$ {command_invocation} --help\n```"
    )
    .expect("writing to a String cannot fail");
    output
}

fn render_arguments(output: &mut String, command: &Command, globals: bool) {
    let arguments = command
        .get_arguments()
        .filter(|argument| argument.get_index().is_none() && argument.is_global_set() == globals)
        .collect::<Vec<_>>();
    let positionals = command
        .get_arguments()
        .filter(|argument| argument.get_index().is_some())
        .collect::<Vec<_>>();

    if !globals && !positionals.is_empty() {
        output.push_str("## Arguments\n\n| Argument | Description |\n| --- | --- |\n");
        for argument in positionals {
            output.push_str(&argument_row(argument));
        }
        output.push('\n');
    }
    if arguments.is_empty() {
        return;
    }
    let heading = if globals { "Global options" } else { "Options" };
    writeln!(
        output,
        "## {heading}\n\n| Option | Description |\n| --- | --- |"
    )
    .expect("writing to a String cannot fail");
    for argument in arguments {
        output.push_str(&argument_row(argument));
    }
    output.push('\n');
}

fn argument_row(argument: &Arg) -> String {
    let syntax = argument_syntax(argument);
    let mut description = argument
        .get_long_help()
        .or_else(|| argument.get_help())
        .map_or_else(|| "—".to_owned(), ToString::to_string);
    let possible = argument
        .get_possible_values()
        .into_iter()
        .filter(|value| !value.is_hide_set())
        .map(|value| value.get_name().to_owned())
        .collect::<Vec<_>>();
    if !possible.is_empty() {
        write!(description, " Values: `{}`.", possible.join("`, `"))
            .expect("writing to a String cannot fail");
    }
    let defaults = argument
        .get_default_values()
        .iter()
        .map(|value| value.to_string_lossy())
        .collect::<Vec<_>>();
    if !defaults.is_empty() {
        write!(description, " Default: `{}`.", defaults.join(" "))
            .expect("writing to a String cannot fail");
    }
    format!(
        "| `{}` | {} |\n",
        escape_table(&syntax),
        escape_table(&description)
    )
}

fn argument_syntax(argument: &Arg) -> String {
    if argument.get_index().is_some() {
        return value_label(argument);
    }
    let mut names = Vec::new();
    if let Some(shorts) = argument.get_short_and_visible_aliases() {
        names.extend(shorts.into_iter().map(|short| format!("-{short}")));
    }
    if let Some(longs) = argument.get_long_and_visible_aliases() {
        names.extend(longs.into_iter().map(|long| format!("--{long}")));
    }
    if let Some(aliases) = argument.get_all_aliases() {
        for alias in aliases {
            let rendered = format!("--{alias}");
            if !names.contains(&rendered) {
                names.push(rendered);
            }
        }
    }
    if argument.get_action().takes_values() {
        names.push(value_label(argument));
    }
    names.join(", ")
}

fn value_label(argument: &Arg) -> String {
    argument.get_value_names().map_or_else(
        || format!("<{}>", argument.get_id().as_str().to_uppercase()),
        |names| {
            names
                .iter()
                .map(|name| format!("<{name}>"))
                .collect::<Vec<_>>()
                .join(" ")
        },
    )
}

fn visible_subcommands(command: &Command) -> impl Iterator<Item = &Command> {
    command
        .get_subcommands()
        .filter(|child| !child.is_hide_set() && child.get_name() != "help")
}

fn command_about(command: &Command) -> String {
    command
        .get_long_about()
        .or_else(|| command.get_about())
        .map_or_else(|| "—".to_owned(), |about| escape_table(&about.to_string()))
}

fn invocation(path: &[String]) -> String {
    std::iter::once("btpc")
        .chain(path.iter().map(String::as_str))
        .collect::<Vec<_>>()
        .join(" ")
}

fn markdown_filename(path: &[String]) -> String {
    if path.is_empty() {
        "index.md".to_owned()
    } else {
        format!("{}.md", path.join("-"))
    }
}

fn escape_table(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}
