import builtins
from collections.abc import Callable
from os import PathLike
from typing import Literal

__gil_required__: Literal[True]
__subinterpreters_supported__: Literal[False]

class _NativeError(Exception):
    offset: int | None
    field: str | None
    path: bytes | None
    limit: str | None
    actual: int | None
    maximum: int | None

class _NativeIoError(_NativeError): ...
class _NativeBencodeSyntaxError(_NativeError): ...
class _NativeBencodeCanonicalError(_NativeError): ...
class _NativeMetainfoError(_NativeError): ...
class _NativeResourceLimitError(_NativeError): ...
class _NativeUnsupportedError(_NativeError): ...
class _NativeVerificationError(_NativeError): ...
class _NativeCancelledError(_NativeError): ...

class _NativeTorrentFile:
    @property
    def length(self) -> int: ...
    @property
    def path(self) -> tuple[bytes, ...]: ...
    @property
    def attributes(self) -> bytes: ...
    @property
    def pieces_root(self) -> bytes | None: ...
    @property
    def is_padding(self) -> bool: ...

class _NativeValidationReport:
    @property
    def warnings(self) -> list[str]: ...
    @property
    def canonical(self) -> bool: ...
    @property
    def canonical_offset(self) -> int | None: ...
    @property
    def canonical_message(self) -> str | None: ...

class _NativeMetainfo:
    @property
    def mode(self) -> str: ...
    @property
    def name(self) -> bytes: ...
    @property
    def piece_length(self) -> int: ...
    @property
    def total_length(self) -> int: ...
    @property
    def piece_count(self) -> int: ...
    @property
    def file_count(self) -> int: ...
    @property
    def files(self) -> tuple[_NativeTorrentFile, ...]: ...
    @property
    def trackers(self) -> tuple[tuple[bytes, ...], ...]: ...
    @property
    def web_seeds(self) -> tuple[bytes, ...]: ...
    @property
    def private(self) -> bool | None: ...
    @property
    def info_hash_v1(self) -> builtins.bytes | None: ...
    @property
    def info_hash_v2(self) -> builtins.bytes | None: ...
    @property
    def original_bytes(self) -> bytes: ...
    @property
    def canonical_bytes(self) -> bytes: ...
    @property
    def canonical_cached(self) -> bool: ...
    @property
    def unknown_fields(self) -> tuple[bytes, ...]: ...
    @property
    def validation(self) -> _NativeValidationReport: ...
    def magnet(self, display_name: bool, trackers: bool, web_seeds: bool) -> str: ...
    def edit(
        self,
        trackers: list[list[bytes]] | None = ...,
        web_seeds: list[bytes] | None = ...,
        nodes: list[tuple[bytes, int]] | None = ...,
        private: bool | None = ...,
        set_private: bool = ...,
        source: bytes | None = ...,
        set_source: bool = ...,
        comment: bytes | None = ...,
        set_comment: bool = ...,
        created_by: bytes | None = ...,
        set_created_by: bool = ...,
        creation_date: int | None = ...,
        set_creation_date: bool = ...,
        raw_top_level: list[tuple[bytes, int | bytes]] = ...,
        file_attributes: list[tuple[list[bytes], bytes]] = ...,
    ) -> _NativeMetainfo: ...
    def verify(
        self,
        payload: str | PathLike[str],
        fail_fast: bool = ...,
        extra_files: bool = ...,
        progress: Callable[[int, int, int], None] | None = ...,
        cancellation: _CancellationToken | None = ...,
    ) -> _NativeVerificationReport: ...

class _NativeCreateResult:
    @property
    def bytes(self) -> builtins.bytes: ...
    @property
    def mode(self) -> str: ...
    @property
    def info_hash_v1(self) -> builtins.bytes | None: ...
    @property
    def info_hash_v2(self) -> builtins.bytes | None: ...
    @property
    def file_count(self) -> int: ...
    @property
    def payload_bytes(self) -> int: ...
    @property
    def piece_count(self) -> int: ...
    @property
    def piece_length(self) -> int: ...
    @property
    def piece_length_policy(self) -> str | None: ...
    @property
    def scan_ms(self) -> float: ...
    @property
    def hash_ms(self) -> float: ...
    @property
    def serialize_ms(self) -> float: ...

class _NativePayloadMismatch:
    @property
    def kind(self) -> str: ...
    @property
    def path(self) -> bytes: ...
    @property
    def piece(self) -> int | None: ...

class _NativeVerificationReport:
    @property
    def mismatches(self) -> tuple[_NativePayloadMismatch, ...]: ...
    @property
    def is_valid(self) -> bool: ...

__version__: str

def inspect_bytes(
    data: object,
    max_total_input: int | None = ...,
    max_owned_allocation: int | None = ...,
    max_integer_digits: int | None = ...,
) -> _NativeMetainfo: ...
def inspect_path(
    path: str | PathLike[str],
    max_total_input: int | None = ...,
    max_owned_allocation: int | None = ...,
    max_integer_digits: int | None = ...,
) -> _NativeMetainfo: ...

class _CancellationToken:
    @property
    def cancelled(self) -> bool: ...
    def cancel(self) -> None: ...

def create_v1(
    path: str | PathLike[str],
    mode: str = ...,
    destination: str | PathLike[str] | None = ...,
    overwrite: bool = ...,
    durable: bool = ...,
    piece_length: int | None = ...,
    threads: int | None = ...,
    trackers: list[list[bytes]] = ...,
    web_seeds: list[bytes] = ...,
    nodes: list[tuple[bytes, int]] = ...,
    private: bool | None = ...,
    source: bytes | None = ...,
    comment: bytes | None = ...,
    created_by: bytes | None = ...,
    omit_created_by: bool = ...,
    creation_date: int | None = ...,
    progress: Callable[[int, int, int], None] | None = ...,
    cancellation: _CancellationToken | None = ...,
) -> _NativeCreateResult: ...
